commerce_adyen.settings:
  type: mapping
  label: Settings
  mapping:
    commerce_adyen_authorise_forcibly:
      type: boolean
    commerce_adyen_disable_automatic_capture_on_authorisation:
      type: boolean

commerce_payment.commerce_payment_gateway.plugin.adyen_boleto:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_account:
      type: string
      label: 'Merchant Account'
    client_user:
      type: string
      label: 'Client User'
    client_password:
      type: string
      label: 'Client Password'
    skin_code:
      type: string
      label: 'Skin Code'
    hmac:
      type: string
      label: 'HMAC key'
    shopper_locale:
      type: string
      label: 'Shopper locale'
    recurring:
      type: string
      label: 'Recurring'
    state:
      type: string
      label: 'State'
    use_checkout_form:
      type: string
      label: 'Use checkout form'

commerce_payment.commerce_payment_gateway.plugin.adyen_openinvoice:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_account:
      type: string
      label: 'Merchant Account'
    client_user:
      type: string
      label: 'Client User'
    client_password:
      type: string
      label: 'Client Password'
    skin_code:
      type: string
      label: 'Skin Code'
    hmac:
      type: string
      label: 'HMAC key'
    shopper_locale:
      type: string
      label: 'Shopper locale'
    recurring:
      type: string
      label: 'Recurring'
    state:
      type: string
      label: 'State'
    use_checkout_form:
      type: string
      label: 'Use checkout form'
