<?php

/**
 * @file
 * Adyen OpenInvoice payments.
 */

use Drupal\commerce_adyen_openinvoice\PaymentController;
use Drupal\commerce_adyen_openinvoice\CheckoutController;

/**
 * Implements hook_commerce_adyen_payment_types().
 */
function commerce_adyen_openinvoice_commerce_adyen_payment_types() {
  $types = [];

  $types['openinvoice'] = [
    'label' => 'OpenInvoice',
    'controllers' => [
      'payment' => PaymentController::class,
      'checkout' => CheckoutController::class,
    ],
  ];

  return $types;
}
