<?php
/**
 * @file
 * Adyen Boleto payments.
 */

/**
 * Implements hook_commerce_adyen_payment_types().
 */
function commerce_adyen_boleto_commerce_adyen_payment_types() {
  $types = [];

  $types['boleto'] = [
    'label' => 'Boleto',
    'controllers' => [
      'payment' => \Commerce\Adyen\Payment\Boleto\PaymentController::class,
      'checkout' => \Commerce\Adyen\Payment\Boleto\CheckoutController::class,
    ],
  ];

  return $types;
}
