<?php

/**
 * @file
 * Adyen Boleto payments.
 */

use Drupal\commerce_adyen_boleto\PaymentController;
use Drupal\commerce_adyen_boleto\CheckoutController;

/**
 * Implements hook_commerce_adyen_payment_types().
 */
function commerce_adyen_boleto_commerce_adyen_payment_types() {
  $types = [];

  $types['boleto'] = [
    'label' => 'Boleto',
    'controllers' => [
      'payment' => PaymentController::class,
      'checkout' => CheckoutController::class,
    ],
  ];

  return $types;
}
